### ISSUE TITLE
Add option to set maxFee to 0

### ISSUE THREAD

**Issue by joeneldeasis** [proximax-storage/tsjs-chain-xipfs-sdk#31]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Network: PRIVATE_TEST

We're using the custom node with zero fees, upon performing document upload we encountered an error `Failed to announce transaction with status Failure_Core_Insufficient_Balance`. In able to fix this I modified the `TransferTransaction.create` in `src/lib/service/blockchain-transaction-service.ts`

Add `UInt64` in the import then modify the code line 174.

Original Code:
```
return TransferTransaction.create(
      Deadline.create(transactionDeadline),
      recipientAddress,
      mosaic,
      message,
      this.networkType
    );
```

Modified Code: I set the `maxFee` here to `UInt64.fromUint(0)`
```
return TransferTransaction.create(
      Deadline.create(transactionDeadline),
      recipientAddress,
      mosaic,
      message,
      this.networkType,
      UInt64.fromUint(0)
    );
```

* **Other information**
Here's the my temporary fix for our zero fees transactions using the sdk: https://github.com/joeneldeasis/tsjs-chain-xipfs-sdk/blob/master/src/lib/service/blockchain-transaction-service.ts

**Comment by thomas-tran** [comment]
Will introduce the network fee calculation strategy in the blockchain config. If not specified, use the default ZeroFeeCalculationStrategy
